package de.h_da.fbi.rfid.companysoftware;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Address.java
//  @ Date : 01.06.2014
//  @ Author : 
//
//




public class Address {
	private String streetname;
	private String housenumber;
	private String zip;
	private String city;

    public Address(String streetname, String housenumber, String zip, String city) {        
        this.streetname = streetname;
        this.housenumber = housenumber;
        this.zip = zip;
        this.city = city;
    }
        
        
}
