package de.h_da.fbi.rfid.companysoftware;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Guest.java
//  @ Date : 01.06.2014
//  @ Author : 
//
//




public class Guest extends Person {
	private String company;

    public Guest(String surname, String name, String cardId, String company) {
        this.surname = surname;
        this.name = name;
        this.cardId = cardId;
        this.company = company;
    }
        
        
}
