package de.h_da.fbi.rfid.companysoftware;

//

import java.util.AbstractCollection;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;


//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersonalManagement.java
//  @ Date : 01.06.2014
//  @ Author : 
//
//




public class PersonalManagement {
	private final List<Person> persons;

    public PersonalManagement() {
        this.persons = new ArrayList<Person>();
    }
    
    public Person addEmployee(String surname, String name, String cardId, String division, int securityClass, String streetname, String housenumber, String zip, String city){
        Person newEmployee = new Employee(surname, name, cardId, division, securityClass, streetname, housenumber, zip, city);
        this.persons.add(newEmployee);
        return newEmployee;
    }
    
    public Person addGuest(String surname, String name, String cardId, String company) {
        Person newGuest = new Guest(surname, name, cardId, company);
        this.persons.add(newGuest);
        return newGuest;
    }
        
    public Person findPerson(String cardId){
            for (Person person : persons) {
                if (person.getCardId().equals(cardId)) {
                    return person;
                }
            }
        return null;
    }
}
