package de.h_da.fbi.rfid.companysoftware;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Person.java
//  @ Date : 01.06.2014
//  @ Author : 
//
//




public abstract class Person {
	protected String surname;
	protected String name;
	protected String cardId;

    /**
     * @return the surname
     */
    public String getSurname() {
        return surname;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @return the cardId
     */
    public String getCardId() {
        return cardId;
    }
        
        
}
